#!/bin/bash

# Copyright (C) 2019 by CPqD

# http://www.dwheeler.com/essays/fixing-unix-linux-filenames.html
set -eu
IFS=$(printf '\n\t')

usage() {
    local name
    name=$(basename "$0")
    echo >&2 "usage: $name [-v] [-l N] [--] ARGS..."
    [[ -n "$1" ]] && exit "$1"
}

VERBOSE=
LIMIT=10
while getopts vl: opt; do
    case $opt in
        v) VERBOSE=1 ;;
        l) LIMIT="$OPTARG" ;;
        \?) usage 1
    esac
done
shift $((OPTIND - 1))

TMPDIR=$(mktemp -d) || exit 1
trap 'rm -rf $TMPDIR' EXIT

[[ -n "$VERBOSE" ]] && set -x

